### ISSUE TITLE
Add grid 2x3

### ISSUE THREAD

**Issue by brenard** [penguin86/ojo#13]
I thanks for this great application! I currently have 6 cameras and when I had more than 4 in the app, the grid pass to max 9 (3x3 grid) directly, without possibly to have  max 6 cameras (2x3 grid). It's could be great to scale grid to max 6 cameras before max 9 cameras.

**Comment by penguin86** [comment]
Hello @brenard,
this is the way the classic surveillance wall works: having all the cameras almost the same aspect ratio, doesn't make a lot of sense to have an uneven grid, as the recovered space will be black anyway.
BTW,  I appreciate your effort, so your merge request has been merged.
Thank you! Have a nice day.
