### ISSUE TITLE
Ubiquiti Rtsp Doesn't Work 

### ISSUE THREAD

**Issue by hakarune** [penguin86/ojo#19]
Ubiquiti rtsp/Rtsps urls don't work. 
rtsps://10.1.1.1:7441/yUCX9KNmaFa8z0Sz?enableSrtp
rtsp://10.1.1.1:7447/yUCX9KNmaFa8z0Sz

![Screenshot_20220603-094936_Ojo.jpg](https://user-images.githubusercontent.com/2251942/171909904-db85f7cd-378e-4938-97f7-0c96fecaaf48.jpg)
![Screenshot_20220603-094927_Ojo.jpg](https://user-images.githubusercontent.com/2251942/171909915-be37cf92-cba3-4d16-9fe4-3bbdc548ece4.jpg)

**Comment by elzershark** [comment]
will never work either. Look at your IP addresses 😉

**Comment by tcables** [comment]
> will never work either. Look at your IP addresses wink

I don't see what OP is missing?

**Comment by BadCo-NZ** [comment]
It looks like OP requires a better solution, an NVR like Frigate with Home Assistant.

**Comment by hakarune** [comment]
> will never work either. Look at your IP addresses 😉

There's nothing wrong with the ips. Multiple camera and video stream apps like VLC and TinyCam play the urls just fine.

**Comment by hakarune** [comment]
> It looks like OP requires a better solution, an NVR like Frigate with Home Assistant.

What? That makes no sense at all. Ubiquiti is an NVR system. I don't need a new NVR or home assistant garbage to use an android app to view my streams.

**Comment by BadCo-NZ** [comment]
> > It looks like OP requires a better solution, an NVR like Frigate with Home Assistant.
> 
> What? That makes no sense at all. Ubiquiti is an NVR system. I don't need a new NVR or home assistant garbage to use an android app to view my streams.

Ubiquiti is a brand. Unifi Protect is the NVR software, which you didn't mention anything about.

If you already have a NVR, why aren't you using the Unifi app to view your streams? (Disclaimer: I have never used Unifi Protect)

Side note: Home Assistant is currently the best open source Home Automation platform that is under constant development by Nabu Casa.

**Comment by penguin86** [comment]
> Ubiquiti rtsp/Rtsps urls don't work. rtsps://10.1.1.1:7441/yUCX9KNmaFa8z0Sz?enableSrtp rtsp://10.1.1.1:7447/yUCX9KNmaFa8z0Sz
> 
> ![Screenshot_20220603-094936_Ojo.jpg](https://user-images.githubusercontent.com/2251942/171909904-db85f7cd-378e-4938-97f7-0c96fecaaf48.jpg) ![Screenshot_20220603-094927_Ojo.jpg](https://user-images.githubusercontent.com/2251942/171909915-be37cf92-cba3-4d16-9fe4-3bbdc548ece4.jpg)

Hello, I'm sorry but I fear there's nothing I can do about it. This app is just a gui for libvlc (https://www.videolan.org/vlc/libvlc.html) so either it does work, or it doesn't.
I can suggest only the basic troubleshooting, just to be sure: check the address is written correctly, try to ping the camera from the phone, try to open the address in VLC from a computer and see if it is play correctly.
One last try may be fiddling with the camera's video encoding settings. You usually access them from a web panel, check your camera's manual to find the address.
