### ISSUE TITLE
F-Droid can't build - appid changed

### ISSUE THREAD

**Issue by licaon-kter** [penguin86/ojo#23]
ref: https://github.com/penguin86/ojo/commit/1647895a2a1084ec17656a80372372d19e41522e#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R9

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3776215384#L900

**Comment by penguin86** [comment]
Thank you for reporting! This should be fixed now with tag v0.1.2, let's wait for F-Droid to pick it up.
