### ISSUE TITLE
VirusTotal detects apk as malware

### ISSUE THREAD

**Issue by iesushartz** [penguin86/ojo#25]
Hello! I hope you are well. I have a concern, when I upload the apk of the app available in the F-Droid repository to the VirusTotal page it gives me as a result that 2 security providers marked the file as malicious (Google and Ikarus). However, this does not happen with the apk hosted on GitHub, why is this?

Best regards

Sorry for my bad English

**Comment by penguin86** [comment]
Hello,
I'm sorry, I don't know. The F-Droid version is automatically built from the F-Droid build system from the master branch of this repository (this can be seen in the F-Droid config repo), but is signed with the F-Droid key. Apart from the signature, the app should be the same.
They may be false positives, I'm pretty sure F-Droid doesn't add any extra code. All the F-Droid build system, configuration and this app's code are open source, this should guarantee the app safety...

**Comment by iesushartz** [comment]
Thanks for the clarification.
