### ISSUE TITLE
Please consider adding RTSP server

### ISSUE THREAD

**Issue by ioctl-user** [penguin86/ojo#7]
Sending camera data from the device could be very usefull.
In this case phone can be used by a desktop as a high quality WEB-camera with ffmpeg and v4l2loopback packages.

**Comment by penguin86** [comment]
Hello @ioctl-user,
thanks for your suggestion. I understand the necessity for an open source rtsp streamer (I'd need one also, but couldn't find), btw this is not the purpose of this app. This app is a simple viewer, like a camera wall surveillance monitor.

Btw, if you know of a well-supported open source library for streaming RTSP that may work on Android, please let me know and I will look into the possibility to develop a separate app for this.
