### ISSUE TITLE
Delete Multicast Address

### ISSUE THREAD

**Issue by OmlineEditor** [penguin86/ojo#9]
I ask you to delete the extra Multicast addresses, I see through the firewall that your program is trying to access these addresses 228.67.43.91, they are not needed for the normal operation of the cameras.

**Comment by penguin86** [comment]
Hello, I'm sorry but I fear there's nothing I can do about it. This app is just a gui for libvlc (https://www.videolan.org/vlc/libvlc.html) and, as you can check in the open source code, it doesn't make any network operation on its own.
Can you confirm the requests are actually coming from this specific app and not from some other code running in background in your phone? You can check this using something like PCAPDroid enabling per-app filtering.
The app has been reviewed for publishing on the F-Droid store, so if it made any kind of tracking requests, it should have been noticed.
If you can confirm the request comes from this app, please file an issue to libvlc: https://www.videolan.org/vlc/libvlc.html
